;this file for FamiTone2 library generated by text2data tool

controll_soundtrack_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Nibbles Title REtroMIX
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; Nibbles Level REtroMIX

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c2,$c7,$cc,$cf,$cb,$c8,$c0,$00,$06


; Nibbles Title REtroMIX
@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $80,$1b,$1f,$23,$1f,$1b,$1f,$22,$85,$1a,$85,$1a,$d5
@song0ch0loop:
@ref1:
	.byte $81
	.byte $fd
	.word @song0ch0loop

; Nibbles Title REtroMIX
@song0ch1:
@ref2:
	.byte $f9,$85
@song0ch1loop:
@ref3:
	.byte $81
	.byte $fd
	.word @song0ch1loop

; Nibbles Title REtroMIX
@song0ch2:
@ref4:
	.byte $f9,$85
@song0ch2loop:
@ref5:
	.byte $81
	.byte $fd
	.word @song0ch2loop

; Nibbles Title REtroMIX
@song0ch3:
@ref6:
	.byte $f9,$85
@song0ch3loop:
@ref7:
	.byte $81
	.byte $fd
	.word @song0ch3loop

; Nibbles Title REtroMIX
@song0ch4:
@ref8:
	.byte $f9,$85
@song0ch4loop:
@ref9:
	.byte $81
	.byte $fd
	.word @song0ch4loop


; Nibbles Level REtroMIX
@song1ch0:
	.byte $fb,$03
@ref10:
	.byte $80,$33,$37,$3b,$37,$33,$37,$3a,$85,$32,$85,$32,$d5
@song1ch0loop:
@ref11:
	.byte $81
	.byte $fd
	.word @song1ch0loop

; Nibbles Level REtroMIX
@song1ch1:
@ref12:
	.byte $f9,$85
@song1ch1loop:
@ref13:
	.byte $81
	.byte $fd
	.word @song1ch1loop

; Nibbles Level REtroMIX
@song1ch2:
@ref14:
	.byte $f9,$85
@song1ch2loop:
@ref15:
	.byte $81
	.byte $fd
	.word @song1ch2loop

; Nibbles Level REtroMIX
@song1ch3:
@ref16:
	.byte $f9,$85
@song1ch3loop:
@ref17:
	.byte $81
	.byte $fd
	.word @song1ch3loop

; Nibbles Level REtroMIX
@song1ch4:
@ref18:
	.byte $f9,$85
@song1ch4loop:
@ref19:
	.byte $81
	.byte $fd
	.word @song1ch4loop
