;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2

@sfx_ntsc_0:
	.byte $83,$b3,$84,$a9,$85,$00,$01,$83,$b5,$01,$83,$b4,$01,$84,$8e,$01
	.byte $83,$b6,$01,$83,$b5,$01,$83,$b6,$84,$7e,$01,$83,$b9,$01,$83,$b7
	.byte $01,$83,$b5,$01,$83,$b3,$02,$00
@sfx_ntsc_1:
	.byte $83,$b4,$84,$a9,$85,$00,$01,$83,$b7,$01,$83,$b6,$01,$83,$b4,$01
	.byte $83,$b2,$02,$83,$b4,$84,$d5,$01,$83,$b6,$01,$83,$b5,$01,$83,$b3
	.byte $01,$83,$b2,$02,$00
@sfx_ntsc_2:
	.byte $80,$bf,$81,$23,$82,$00,$01,$80,$ba,$81,$1b,$01,$80,$b8,$81,$1d
	.byte $01,$80,$b5,$81,$17,$01,$80,$b6,$81,$15,$01,$80,$b4,$81,$11,$01
	.byte $80,$b1,$81,$1a,$01,$00
