;this file for FamiTone2 library generated by FamiStudio

retropia_soundtrack_music_data:
	.byte 11
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,307,256

@instruments:
	.byte $30 ;instrument 00 (Arpeggioish)
	.word @env6, @env17, @env0
	.byte $00
	.byte $30 ;instrument 01 (BassDrum)
	.word @env1, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 02 (Bassish)
	.word @env19, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 03 (GKBacking)
	.word @env2, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 04 (GKFanfare)
	.word @env5, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 05 (GKLead)
	.word @env4, @env0, @env0
	.byte $00
	.byte $f0 ;instrument 06 (Lead)
	.word @env18, @env0, @env0
	.byte $00
	.byte $30 ;instrument 07 (Noise-Bumbo (F#2))
	.word @env12, @env11, @env0
	.byte $00
	.byte $30 ;instrument 08 (NoiseHiHat)
	.word @env3, @env0, @env0
	.byte $00
	.byte $30 ;instrument 09 (Noise-Prato (D#2))
	.word @env8, @env10, @env0
	.byte $00
	.byte $30 ;instrument 0a (NoiseSnare)
	.word @env13, @env0, @env0
	.byte $00
	.byte $70 ;instrument 0b (SimpleBacking)
	.word @env16, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 0c (SimpleLead)
	.word @env15, @env0, @env0
	.byte $00
	.byte $30 ;instrument 0d (Tri-Bumbo)
	.word @env20, @env0, @env9
	.byte $00
	.byte $30 ;instrument 0e (Tri-Caixa)
	.word @env7, @env0, @env14
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c5,$cc,$c9,$c6,$c4,$c2,$00,$05
@env2:
	.byte $c7,$c3,$02,$c2,$c0,$00,$04
@env3:
	.byte $cf,$cd,$ca,$c0,$00,$03
@env4:
	.byte $c5,$c8,$ca,$c7,$c4,$c0,$00,$05
@env5:
	.byte $c1,$c3,$c5,$c6,$c7,$c8,$c7,$c5,$00,$07
@env6:
	.byte $cc,$cb,$ca,$c7,$c5,$c3,$c2,$c1,$00,$07
@env7:
	.byte $cf,$02,$c0,$00,$02
@env8:
	.byte $c8,$c6,$02,$c0,$00,$03
@env9:
	.byte $c0,$f9,$00,$01
@env10:
	.byte $c0,$c3,$00,$01
@env11:
	.byte $c3,$be,$bf,$00,$02
@env12:
	.byte $cb,$ca,$c8,$c6,$c4,$c2,$c0,$00,$06
@env13:
	.byte $cf,$cd,$cb,$c9,$c7,$c6,$c4,$c2,$00,$07
@env14:
	.byte $c0,$84,$00,$01
@env15:
	.byte $c6,$c8,$c6,$c5,$c4,$c3,$00,$05
@env16:
	.byte $c5,$c6,$c4,$c3,$c2,$c1,$00,$05
@env17:
	.byte $c0,$c3,$c7,$c0,$00,$03
@env18:
	.byte $c8,$17,$c7,$c6,$c5,$c4,$c3,$02,$c2,$02,$c1,$04,$c0,$00,$0c
@env19:
	.byte $c1,$c3,$c4,$c5,$c6,$c5,$c6,$c5,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$0f
@env20:
	.byte $cf,$05,$c0,$c0,$c0,$00,$04

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $a1,$8c,$30,$bb,$38,$9d,$46,$f9,$83
@ref1:
	.byte $48,$8d,$44,$8d,$48,$9d,$40,$9d,$3a,$9d,$40,$ed,$00,$8d
@ref2:
	.byte $a1,$30,$bb,$38,$9d,$46,$f9,$83
@ref3:
	.byte $46,$bd,$38,$9d,$3c,$9d,$40,$9b,$3c,$9d,$38,$af,$00,$8d
@ref4:
	.byte $9f,$38,$9d,$3c,$9d,$4a,$bd,$42,$dd
@ref5:
	.byte $46,$bd,$50,$8d,$4c,$8d,$46,$8d,$3c,$8d,$42,$8d,$34,$9d,$34,$9d,$3c,$ad
	.byte $ff,$08
	.word @ref2
	.byte $ff,$0e
	.word @ref3
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref6:
	.byte $84,$12,$9d,$16,$9d,$1c,$9d,$16,$9d,$12,$9d,$16,$9d,$1c,$9d,$16,$9d
@ref7:
	.byte $1a,$9d,$20,$9d,$28,$9d,$20,$9d,$1a,$9d,$20,$9d,$28,$9d,$20,$9d
@ref8:
	.byte $12,$9d,$16,$9d,$1c,$9d,$16,$9d,$12,$9d,$16,$9d,$1c,$9d,$16,$9d
	.byte $ff,$10
	.word @ref7
	.byte $ff,$10
	.word @ref8
	.byte $ff,$10
	.word @ref7
	.byte $ff,$10
	.word @ref8
	.byte $ff,$10
	.word @ref7
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref9:
	.byte $9a,$26,$8d,$00,$ad,$26,$8d,$00,$ad,$26,$8d,$00,$8d,$9c,$2a,$9d,$9a,$26,$8d,$00,$8d,$9c,$2a,$9d
	.byte $ff,$14
	.word @ref9
	.byte $ff,$14
	.word @ref9
	.byte $ff,$14
	.word @ref9
	.byte $ff,$14
	.word @ref9
	.byte $ff,$14
	.word @ref9
	.byte $ff,$14
	.word @ref9
	.byte $ff,$14
	.word @ref9
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref10:
	.byte $8e,$3c,$9d,$92,$38,$8d,$38,$8d,$8e,$3c,$9d,$92,$38,$8d,$8e,$3c,$ad,$92,$38,$8d,$38,$8d,$8e,$3c,$9d,$92,$38,$9d
	.byte $ff,$14
	.word @ref10
	.byte $ff,$14
	.word @ref10
	.byte $ff,$14
	.word @ref10
	.byte $ff,$14
	.word @ref10
	.byte $ff,$14
	.word @ref10
	.byte $ff,$14
	.word @ref10
	.byte $ff,$14
	.word @ref10
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref11:
	.byte $f9,$f9,$8b
@ref12:
	.byte $f9,$f9,$8b
@ref13:
	.byte $f9,$f9,$8b
@ref14:
	.byte $f9,$f9,$8b
@ref15:
	.byte $f9,$f9,$8b
@ref16:
	.byte $f9,$f9,$8b
@ref17:
	.byte $f9,$f9,$8b
@ref18:
	.byte $f9,$f9,$8b
	.byte $fd
	.word @song0ch4loop

@song1ch0:
	.byte $fb, $01
@ref19:
	.byte $98,$4a,$99,$52,$b5,$62,$b3,$00,$62,$b7,$00,$97
@song1ch0loop:
@ref20:
	.byte $98,$4a,$ed,$50,$99,$54,$99,$46,$a7,$4a,$8b
@ref21:
	.byte $4a,$d1,$4e,$99,$52,$99,$4e,$99,$48,$b5
@ref22:
	.byte $40,$99,$48,$99,$40,$8b,$4a,$8b,$44,$8b,$40,$a7,$48,$b5,$40,$99
@ref23:
	.byte $4a,$99,$52,$99,$4a,$8b,$54,$8b,$4e,$8b,$4a,$a7,$52,$b5,$4a,$99
@ref24:
	.byte $44,$99,$40,$99,$4a,$8b,$44,$8b,$48,$8b,$4a,$a7,$44,$b5,$40,$97,$00
@ref25:
	.byte $4a,$ed,$54,$99,$42,$99,$54,$99,$4a,$99
@ref26:
	.byte $50,$ed,$5a,$99,$48,$99,$5a,$99,$50,$99
@ref27:
	.byte $4a,$b3,$00,$9b,$48,$8b,$42,$8b,$46,$8b,$3e,$8b,$42,$8b,$3a,$8b,$3e,$8b,$36,$8b,$38,$97,$00
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@ref28:
	.byte $96,$40,$99,$4a,$b5,$52,$b3,$00,$52,$b3,$00,$9b
@song1ch1loop:
@ref29:
	.byte $96,$40,$ed,$46,$99,$42,$99,$3c,$b5
@ref30:
	.byte $40,$d1,$44,$b5,$46,$99,$3e,$b5
@ref31:
	.byte $36,$99,$32,$99,$38,$8b,$30,$8b,$28,$8b,$28,$99,$2e,$8b,$36,$b5,$2e,$99
@ref32:
	.byte $32,$99,$2e,$99,$34,$8b,$2c,$8b,$24,$8b,$24,$99,$2a,$8b,$32,$b5,$2a,$99
@ref33:
	.byte $3c,$99,$38,$99,$42,$8b,$3a,$c3,$32,$b5,$3a,$97,$00
@ref34:
	.byte $40,$ed,$48,$99,$4a,$99,$40,$b5
@ref35:
	.byte $46,$ed,$3e,$99,$42,$99,$46,$b3,$00
@ref36:
	.byte $3e,$b3,$00,$9b,$3e,$8b,$3a,$8b,$42,$8b,$38,$8b,$3e,$8b,$32,$8b,$2e,$b3,$00
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@ref37:
	.byte $82,$20,$97,$00,$96,$28,$97,$00,$28,$97,$00,$28,$99,$82,$20,$97,$00,$96,$32,$97,$00,$32,$97,$00,$32,$99
@song1ch2loop:
@ref38:
	.byte $82,$20,$97,$00,$96,$32,$97,$00,$32,$97,$00,$32,$97,$00,$82,$20,$97,$00,$96,$32,$97,$00,$32,$97,$00,$32,$99
	.byte $ff,$16
	.word @ref37
	.byte $ff,$17
	.word @ref38
	.byte $ff,$16
	.word @ref37
	.byte $ff,$17
	.word @ref38
	.byte $ff,$16
	.word @ref37
	.byte $ff,$17
	.word @ref38
	.byte $ff,$16
	.word @ref37
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@ref39:
	.byte $90,$7a,$b3,$00,$9b,$7a,$99,$00,$b5,$7a,$b3,$00
@song1ch3loop:
@ref40:
	.byte $90,$7a,$b5,$94,$76,$99,$90,$7a,$99,$94,$76,$b5,$90,$7a,$b5
@ref41:
	.byte $7a,$b5,$94,$76,$99,$90,$7a,$99,$94,$76,$b5,$90,$7a,$b5
	.byte $ff,$0a
	.word @ref41
	.byte $ff,$0a
	.word @ref41
	.byte $ff,$0a
	.word @ref41
	.byte $ff,$0a
	.word @ref41
	.byte $ff,$0a
	.word @ref41
	.byte $ff,$0a
	.word @ref41
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@ref42:
	.byte $f9,$e5
@song1ch4loop:
@ref43:
	.byte $f9,$e5
@ref44:
	.byte $f9,$e5
@ref45:
	.byte $f9,$e5
@ref46:
	.byte $f9,$e5
@ref47:
	.byte $f9,$e5
@ref48:
	.byte $f9,$e5
@ref49:
	.byte $f9,$e5
@ref50:
	.byte $f9,$e5
	.byte $fd
	.word @song1ch4loop

@song2ch0:
	.byte $fb, $01
@ref51:
	.byte $98,$1a,$8f,$00,$9d,$50,$87,$56,$87,$54,$87,$5a,$87,$64,$87,$60,$8f,$00
@song2ch0loop:
@ref52:
	.byte $f7
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref53:
	.byte $b1,$96,$46,$87,$4a,$87,$46,$87,$4a,$87,$50,$87,$54,$8f,$00
@song2ch1loop:
@ref54:
	.byte $f7
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref55:
	.byte $f7
@song2ch2loop:
@ref56:
	.byte $f7
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref57:
	.byte $f7
@song2ch3loop:
@ref58:
	.byte $f7
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref59:
	.byte $f7
@song2ch4loop:
@ref60:
	.byte $f7
	.byte $fd
	.word @song2ch4loop

@song3ch0:
	.byte $fb, $01
@ref61:
	.byte $8a,$2e,$cd,$3a,$a5
@ref62:
	.byte $93,$26,$91,$3a,$91,$1a,$91,$26,$a5
@song3ch0loop:
@ref63:
	.byte $8a,$2e,$a5,$1a,$91,$28,$91,$3a,$a5
@ref64:
	.byte $1a,$91,$26,$91,$3a,$91,$1a,$91,$26,$a5
@ref65:
	.byte $34,$a5,$20,$91,$2e,$91,$40,$a5
@ref66:
	.byte $20,$91,$2c,$91,$40,$91,$20,$91,$2c,$a5
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref67:
	.byte $f7
@ref68:
	.byte $f7
@song3ch1loop:
@ref69:
	.byte $86,$26,$a5,$12,$91,$20,$91,$28,$a5
@ref70:
	.byte $12,$91,$2c,$91,$32,$91,$12,$91,$1e,$a5
@ref71:
	.byte $26,$a5,$12,$91,$20,$91,$28,$a5
	.byte $ff,$0a
	.word @ref70
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref72:
	.byte $f7
@ref73:
	.byte $f7
@song3ch2loop:
@ref74:
	.byte $f7
@ref75:
	.byte $f7
@ref76:
	.byte $f7
@ref77:
	.byte $f7
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref78:
	.byte $f7
@ref79:
	.byte $f7
@song3ch3loop:
@ref80:
	.byte $f7
@ref81:
	.byte $f7
@ref82:
	.byte $f7
@ref83:
	.byte $f7
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref84:
	.byte $f7
@ref85:
	.byte $f7
@song3ch4loop:
@ref86:
	.byte $f7
@ref87:
	.byte $f7
@ref88:
	.byte $f7
@ref89:
	.byte $f7
	.byte $fd
	.word @song3ch4loop

@song4ch0:
	.byte $fb, $01
@ref90:
	.byte $88,$3a,$cd,$42,$cd,$3e,$cb,$00
@song4ch0loop:
@ref91:
	.byte $88,$42,$91,$44,$91,$40,$91,$40,$91,$46,$91,$46,$91,$4a,$91,$4a,$91,$40,$91,$3c,$91,$3c,$a5
@ref92:
	.byte $3c,$91,$3e,$91,$3a,$91,$3a,$91,$42,$91,$42,$91,$46,$91,$46,$91,$40,$91,$4a,$91,$4a,$a5
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@ref93:
	.byte $84,$32,$cd,$2c,$cd,$32,$a5,$2e,$a3,$00
@song4ch1loop:
@ref94:
	.byte $84,$30,$a5,$32,$a5,$2e,$a5,$32,$a5,$2c,$a5,$2e,$a5
@ref95:
	.byte $30,$a5,$32,$a5,$2e,$a5,$32,$a5,$2c,$a5,$2e,$a5
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@ref96:
	.byte $f9,$f5
@song4ch2loop:
@ref97:
	.byte $f9,$f5
@ref98:
	.byte $f9,$f5
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@ref99:
	.byte $f9,$f5
@song4ch3loop:
@ref100:
	.byte $f9,$f5
@ref101:
	.byte $f9,$f5
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@ref102:
	.byte $f9,$f5
@song4ch4loop:
@ref103:
	.byte $f9,$f5
@ref104:
	.byte $f9,$f5
	.byte $fd
	.word @song4ch4loop

@song5ch0:
	.byte $fb, $01
@ref105:
	.byte $8a,$44,$a5,$48,$91,$4a,$91,$44,$a5,$40,$a5,$3c,$91,$3e,$91,$44,$a5
@song5ch0loop:
@ref106:
	.byte $8a,$4a,$91,$48,$91,$4e,$91,$50,$91,$4a,$a5,$46,$a5,$42,$91,$44,$91,$4a,$a5
@ref107:
	.byte $44,$91,$48,$91,$4e,$91,$4a,$91,$44,$a5,$48,$a5,$40,$91,$48,$91,$44,$a5
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@ref108:
	.byte $f9,$f5
@song5ch1loop:
@ref109:
	.byte $86,$3c,$a5,$42,$a7,$3c,$cb,$36,$a5,$3c,$a5
@ref110:
	.byte $38,$a5,$40,$a5,$38,$a7,$3a,$a3,$32,$a5,$38,$a5
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@ref111:
	.byte $f9,$f5
@song5ch2loop:
@ref112:
	.byte $f9,$f5
@ref113:
	.byte $f9,$f5
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@ref114:
	.byte $f9,$f5
@song5ch3loop:
@ref115:
	.byte $f9,$f5
@ref116:
	.byte $f9,$f5
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@ref117:
	.byte $f9,$f5
@song5ch4loop:
@ref118:
	.byte $f9,$f5
@ref119:
	.byte $f9,$f5
	.byte $fd
	.word @song5ch4loop

@song6ch0:
	.byte $fb, $01
@ref120:
	.byte $8a,$3c,$91,$40,$91,$44,$91,$40,$91,$3c,$91,$40,$91,$44,$a5,$3c,$a5,$3c,$a5
@song6ch0loop:
@ref121:
	.byte $88,$3c,$a5,$44,$91,$3c,$91,$4a,$a5,$3c,$91,$44,$91,$54,$a5,$44,$a5
@ref122:
	.byte $3c,$a5,$44,$91,$4a,$91,$3c,$a5,$4a,$91,$54,$91,$3c,$a5,$44,$a3,$00
	.byte $fd
	.word @song6ch0loop

@song6ch1:
@ref123:
	.byte $f9,$f5
@song6ch1loop:
@ref124:
	.byte $84,$32,$a5,$3a,$a5,$32,$a5,$3a,$a5,$32,$a5,$32,$a5
@ref125:
	.byte $32,$a5,$36,$a5,$36,$a5,$32,$a5,$40,$a5,$36,$a5
	.byte $fd
	.word @song6ch1loop

@song6ch2:
@ref126:
	.byte $f9,$f5
@song6ch2loop:
@ref127:
	.byte $f9,$f5
@ref128:
	.byte $f9,$f5
	.byte $fd
	.word @song6ch2loop

@song6ch3:
@ref129:
	.byte $f9,$f5
@song6ch3loop:
@ref130:
	.byte $f9,$f5
@ref131:
	.byte $f9,$f5
	.byte $fd
	.word @song6ch3loop

@song6ch4:
@ref132:
	.byte $f9,$f5
@song6ch4loop:
@ref133:
	.byte $f9,$f5
@ref134:
	.byte $f9,$f5
	.byte $fd
	.word @song6ch4loop

@song7ch0:
	.byte $fb, $01
@ref135:
	.byte $88,$3a,$91,$42,$91,$4a,$91,$48,$91,$46,$91,$48,$91,$4a,$a3,$00,$93,$44,$91,$4a,$a3,$00
@song7ch0loop:
@ref136:
	.byte $f9,$f5
@ref137:
	.byte $f9,$f5
	.byte $fd
	.word @song7ch0loop

@song7ch1:
@ref138:
	.byte $84,$32,$91,$3a,$91,$42,$91,$40,$91,$3e,$91,$3c,$91,$3a,$a3,$00,$93,$3c,$91,$38,$a5
@song7ch1loop:
@ref139:
	.byte $f9,$f5
@ref140:
	.byte $f9,$f5
	.byte $fd
	.word @song7ch1loop

@song7ch2:
@ref141:
	.byte $f9,$f5
@song7ch2loop:
@ref142:
	.byte $f9,$f5
@ref143:
	.byte $f9,$f5
	.byte $fd
	.word @song7ch2loop

@song7ch3:
@ref144:
	.byte $f9,$f5
@song7ch3loop:
@ref145:
	.byte $f9,$f5
@ref146:
	.byte $f9,$f5
	.byte $fd
	.word @song7ch3loop

@song7ch4:
@ref147:
	.byte $f9,$f5
@song7ch4loop:
@ref148:
	.byte $f9,$f5
@ref149:
	.byte $f9,$f5
	.byte $fd
	.word @song7ch4loop

@song8ch0:
	.byte $fb, $01
@ref150:
	.byte $88,$3a,$a5,$34,$a5,$36,$a5,$34,$a5,$2e,$cb,$00
@song8ch0loop:
@ref151:
	.byte $f9,$f5
@ref152:
	.byte $f9,$f5
	.byte $fd
	.word @song8ch0loop

@song8ch1:
@ref153:
	.byte $84,$24,$cd,$2a,$a5,$28,$a5,$24,$cb,$00
@song8ch1loop:
@ref154:
	.byte $f9,$f5
@ref155:
	.byte $f9,$f5
	.byte $fd
	.word @song8ch1loop

@song8ch2:
@ref156:
	.byte $f9,$f5
@song8ch2loop:
@ref157:
	.byte $f9,$f5
@ref158:
	.byte $f9,$f5
	.byte $fd
	.word @song8ch2loop

@song8ch3:
@ref159:
	.byte $f9,$f5
@song8ch3loop:
@ref160:
	.byte $f9,$f5
@ref161:
	.byte $f9,$f5
	.byte $fd
	.word @song8ch3loop

@song8ch4:
@ref162:
	.byte $f9,$f5
@song8ch4loop:
@ref163:
	.byte $f9,$f5
@ref164:
	.byte $f9,$f5
	.byte $fd
	.word @song8ch4loop

@song9ch0:
	.byte $fb, $01
@ref165:
	.byte $80,$3c,$99,$3e,$99,$4e,$99,$48,$99,$44,$b5,$4e,$b5
@song9ch0loop:
@ref166:
	.byte $80,$4e,$8b,$4a,$8b,$4e,$8b,$3c,$8b,$42,$8b,$3c,$99,$50,$8b,$4a,$8b,$44,$8b,$40,$99,$54,$99,$52,$99
@ref167:
	.byte $4c,$99,$50,$8b,$52,$8b,$58,$8b,$40,$8b,$44,$8b,$40,$8b,$4c,$97,$4c,$9b,$52,$8b,$4e,$8b,$4a,$8b,$4a,$8b
@ref168:
	.byte $3e,$99,$42,$99,$46,$99,$4a,$99,$44,$99,$48,$99,$4c,$99,$50,$99
@ref169:
	.byte $58,$b7,$56,$99,$52,$99,$4e,$99,$4a,$cf
@ref170:
	.byte $44,$b5,$32,$b5,$3c,$b5,$44,$8b,$3c,$8b,$44,$97,$00
@ref171:
	.byte $4c,$b5,$48,$b5,$44,$b5,$4e,$8b,$48,$8b,$40,$8b,$3a,$89,$00
	.byte $ff,$0d
	.word @ref170
	.byte $ff,$0f
	.word @ref171
	.byte $fd
	.word @song9ch0loop

@song9ch1:
@ref172:
	.byte $84,$32,$b5,$44,$99,$3e,$99,$3a,$b5,$44,$b5
@song9ch1loop:
@ref173:
	.byte $84,$3a,$b5,$32,$b5,$3a,$b5,$32,$99,$36,$99
@ref174:
	.byte $42,$b5,$3a,$b5,$42,$b5,$3c,$99,$36,$99
@ref175:
	.byte $36,$99,$3a,$99,$3e,$99,$42,$99,$3a,$99,$3e,$99,$42,$99,$46,$99
@ref176:
	.byte $4a,$b5,$40,$b5,$38,$99,$38,$d1
@ref177:
	.byte $38,$b5,$2a,$b5,$2e,$b5,$2c,$8b,$2e,$8b,$2c,$8b,$2e,$89,$00
@ref178:
	.byte $36,$b5,$32,$b5,$36,$b5,$32,$8b,$36,$8b,$3a,$8b,$36,$89,$00
	.byte $ff,$0f
	.word @ref177
	.byte $ff,$0f
	.word @ref178
	.byte $fd
	.word @song9ch1loop

@song9ch2:
@ref179:
	.byte $f9,$e5
@song9ch2loop:
@ref180:
	.byte $9a,$18,$b5,$18,$99,$9c,$1c,$99,$9a,$18,$b5,$18,$99,$9c,$1c,$99
	.byte $ff,$0c
	.word @ref180
	.byte $ff,$0c
	.word @ref180
	.byte $ff,$0c
	.word @ref180
	.byte $ff,$0c
	.word @ref180
	.byte $ff,$0c
	.word @ref180
	.byte $ff,$0c
	.word @ref180
	.byte $ff,$0c
	.word @ref180
	.byte $fd
	.word @song9ch2loop

@song9ch3:
@ref181:
	.byte $92,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$38,$89,$00
@song9ch3loop:
@ref182:
	.byte $92,$38,$8b,$38,$8b,$8e,$3e,$99,$92,$38,$8b,$38,$8b,$8e,$3e,$99,$92,$38,$8b,$38,$8b,$8e,$3e,$99,$3e,$99,$3e,$97,$00
	.byte $ff,$17
	.word @ref182
	.byte $ff,$17
	.word @ref182
	.byte $ff,$17
	.word @ref182
	.byte $ff,$17
	.word @ref182
	.byte $ff,$17
	.word @ref182
	.byte $ff,$17
	.word @ref182
	.byte $ff,$17
	.word @ref182
	.byte $fd
	.word @song9ch3loop

@song9ch4:
@ref183:
	.byte $f9,$e5
@song9ch4loop:
@ref184:
	.byte $f9,$e5
@ref185:
	.byte $f9,$e5
@ref186:
	.byte $f9,$e5
@ref187:
	.byte $f9,$e5
@ref188:
	.byte $f9,$e5
@ref189:
	.byte $f9,$e5
@ref190:
	.byte $f9,$e5
@ref191:
	.byte $f9,$e5
	.byte $fd
	.word @song9ch4loop

@song10ch0:
	.byte $fb, $01
@ref192:
	.byte $88,$3c,$8b,$44,$8b,$4c,$8b,$4a,$8b,$48,$8b,$4a,$8b,$4c,$97,$00,$9b,$46,$99,$4c,$b3,$00
@song10ch0loop:
@ref193:
	.byte $88,$54,$99,$4e,$8b,$52,$99,$4a,$8b,$4e,$99,$54,$99,$4c,$8b,$52,$8b,$4e,$b5
@ref194:
	.byte $54,$99,$4e,$99,$4a,$99,$4e,$99,$54,$99,$4a,$99,$4e,$99,$4e,$99
@ref195:
	.byte $54,$99,$5c,$99,$4a,$b5,$54,$99,$4a,$99,$4e,$99,$52,$99
@ref196:
	.byte $58,$a7,$44,$8b,$54,$99,$4c,$99,$46,$99,$44,$cf,$00
	.byte $fd
	.word @song10ch0loop

@song10ch1:
@ref197:
	.byte $96,$36,$99,$32,$99,$30,$99,$36,$b5,$3a,$99,$36,$b3,$00
@song10ch1loop:
@ref198:
	.byte $96,$36,$99,$32,$99,$36,$99,$2e,$99,$38,$99,$32,$99,$38,$b5
@ref199:
	.byte $3e,$99,$3e,$99,$3a,$99,$3e,$99,$42,$99,$46,$99,$3e,$b5
@ref200:
	.byte $44,$99,$4a,$a7,$40,$a7,$44,$99,$4a,$b5,$40,$99
@ref201:
	.byte $4e,$a7,$3a,$8b,$42,$99,$3a,$99,$34,$99,$36,$d1
	.byte $fd
	.word @song10ch1loop

@song10ch2:
@ref202:
	.byte $f9,$e5
@song10ch2loop:
@ref203:
	.byte $9c,$1a,$b5,$1a,$b5,$1a,$b5,$1a,$99,$1a,$99
@ref204:
	.byte $1a,$b5,$1a,$b5,$1a,$b5,$1a,$99,$1a,$99
	.byte $ff,$0a
	.word @ref204
	.byte $ff,$0a
	.word @ref204
	.byte $fd
	.word @song10ch2loop

@song10ch3:
@ref205:
	.byte $92,$38,$b5,$38,$b5,$38,$b5,$38,$b5
@song10ch3loop:
@ref206:
	.byte $92,$38,$99,$38,$99,$8e,$3e,$99,$92,$38,$99,$38,$8b,$38,$8b,$38,$8b,$38,$8b,$8e,$3e,$99,$3e,$99
	.byte $ff,$14
	.word @ref206
	.byte $ff,$14
	.word @ref206
	.byte $ff,$14
	.word @ref206
	.byte $fd
	.word @song10ch3loop

@song10ch4:
@ref207:
	.byte $f9,$e5
@song10ch4loop:
@ref208:
	.byte $f9,$e5
@ref209:
	.byte $f9,$e5
@ref210:
	.byte $f9,$e5
@ref211:
	.byte $f9,$e5
	.byte $fd
	.word @song10ch4loop
